name: Backend Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - gateway
          - auth-service
          - user-service
          - match-service
          - player-service
          - s3-upload-service
          - elo-service
          - tournament-service

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push Docker image for ${{ matrix.service }}
        run: |
          IMAGE_NAME=${{ matrix.service }}
          ECR_REPOSITORY=970547372113.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_NAME
          docker buildx build --platform linux/amd64 -t $IMAGE_NAME:latest ./backend/${{ matrix.service }} --load
          docker tag $IMAGE_NAME:latest $ECR_REPOSITORY:latest
          docker push $ECR_REPOSITORY:latest

      - name: Deploy to Amazon ECS for ${{ matrix.service }}
        run: |
          aws ecs update-service \
            --cluster chess-tms-cluster \
            --service ${{ matrix.service }} \
            --force-new-deployment \
            --region us-east-1